title: Kai Chang
theme: jekyll-theme-minimal
description: >
  Aspiring Data Analyst (SQL | Python)
  
  Bachelor of Science in Biology
  
  <a href="https://www.linkedin.com/">View My LinkedIn Profile - Test</a>
google_analytics: UA-159843749-1
