title: Kai Chang
theme: jekyll-theme-minimal
logo: "https://raw.githubusercontent.com/kaichang1/kaichang1.github.io/master/Images/Profile%20Picture.png"
description: >
  Hello!
  <br>
  <a href="https://www.linkedin.com/in/kai-hsiang-chang/">View My LinkedIn Profile</a>
google_analytics: UA-159843749-1
